- name: Fix it now
  pattern: "[fF][iI][xX][mM][eE]"
  filePattern: ".*.py$"

- name: IPython debug leftover
  pattern: "IPython\\.embed()"
  filePattern: ".*.py$"

- name: Use relative imports
  pattern: "^import levo|^from levo"
  filePattern: "src/.*.py$"
