swagger: "2.0"
info:
  description: "This is a demo server that is deliberately vulnerable to Server Side Request Forgery (SSRF) attacks."
  version: "1.0.0"
  title: "Levo SSRF Demo"
  termsOfService: "http://levo.ai/terms/"
  contact:
    email: "info@levo.ai"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
externalDocs:
  description: Find out more about Levo.ai
  url: http://levo.ai
host: "localhost:5000"
basePath: "/"
tags:
  - name: ssrfmap
    description: For testing SSRFmap modules.
    externalDocs:
      description: SSRFmap on GitHub
      url: http://github.com/levoai/SSRFmap
schemes:
- "http"
paths:
  /form-data:
    post:
      tags:
      - "ssrfmap"
      summary: "Deliberately vulnerable SSRF (Form Data) endpoint."
      description: "Sends an HTTP POST request to a URL accepted as a form data parameter."
      operationId: "post-form-data"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "*/*"
      parameters:
      - in: formData
        name: url
        type: string
        description: The URL to fetch.
        required: true
      responses:
        '200':
          description: successful operation
          schema:
            type: "string"
  /json:
    post:
      tags:
      - "ssrfmap"
      summary: "Deliberately vulnerable SSRF (JSON) endpoint."
      description: "Sends an HTTP POST request to a URL accepted in a JSON body."
      operationId: "post-json"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: body
        name: url
        required: true
        description: The JSON request body.
        schema:
          type: object
          required:
            - url
          properties:
            url:
              type: string
              example: https://example.com
      responses:
        '200':
          description: successful operation
          schema:
            type: "string"
  /query-string:
    get:
      tags:
      - "ssrfmap"
      summary: "Deliberately vulnerable SSRF (Query String) endpoint."
      description: "Sends an HTTP GET request to a URL accepted as a query string parameter."
      operationId: "get-query-string"
      produces:
      - "*/*"
      parameters:
      - in: query
        name: url
        type: string
        required: true
        description: The URL to fetch.
      responses:
        '200':
          description: successful operation
          schema:
            type: "string"
  /xml:
    post:
      tags:
      - "ssrfmap"
      summary: "Deliberately vulnerable SSRF (XML) endpoint."
      description: "Sends an HTTP POST request to a URL accepted in an XML body."
      operationId: "post-xml"
      consumes:
      - "application/xml"
      produces:
      - "*/*"
      parameters:
      - in: body
        name: url
        description: The URL to fetch.
        schema:
          type: object
          required:
            - url
          properties:
            url:
              type: string
              example: https://example.com
          xml:
            name: run

      responses:
        '200':
          description: successful operation
          schema:
            type: "string"
